name: End2End Workflow

on:
  workflow_dispatch:   
env:
  
  SLN_FILE: PartsUnlimited-aspnet45\PartsUnlimited.sln
 
jobs:
  build:
    name: BUILD USING VS2019
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.5
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1
      - name: NuGet restore
        run: nuget restore
      - name: BuildApp
        run: |
          msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{github.workspace}}\stagingdir"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{github.workspace}}\stagingdir

  deploy:
    name: Download artifacts
    runs-on: windows-new
    needs: [build]
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: drop
          path: ${{github.workspace}}
      - name: Extract Artifact
        run: expand-archive -path '*.zip' -destinationpath '.\webapp'
        shell: pwsh
