name: Test for powershell

on:
  workflow_dispatch:   

jobs:
  build:
    name: Test
    runs-on: windows-latest
    steps:
        
      - name: Powershell Test
        shell: pwsh
        run: |
          & '.\testpowershell.ps1'
